name: Publish
on:
   push:
      branches:
         - main
permissions:
   contents: write
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
   publish:
      runs-on: 'ubuntu-latest'
      steps:
         - uses: actions/checkout@v3
         - uses: pnpm/action-setup@v2
           with:
              version: 7
         - uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node }}
              cache: 'pnpm'
         - run: pnpm install --frozen-lockfile
         - run: pnpm build

         # - name: Deploy 🚀
         #   uses: JamesIves/github-pages-deploy-action@v4
         #   with:
         #      folder: dist
         - run: git config user.name "Ashish-simplCoder" && git config user.email "ashish.simplecoder@gmail.com" && pnpm build && pnpm gh-deploy
